image: docker

before_script:
  - docker login registry.roqua.nl -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"

.test_build: &test_build
  retry: 2
  script:
    # Hack to set an array in /bin/sh
    # http://unix.stackexchange.com/a/137571
    - set -- $CI_JOB_NAME
    - docker build --pull -f "Dockerfile.$1" .
  except:
    - master

.build_and_deploy: &build_and_deploy
  retry: 2
  script:
    - docker build --pull --no-cache -t "registry.roqua.nl/$CI_PROJECT_PATH:$CI_JOB_NAME" -f "Dockerfile.$CI_JOB_NAME" .
    - docker push "registry.roqua.nl/$CI_PROJECT_PATH:$CI_JOB_NAME"
  only:
    - master

elixir-1.5 test: *test_build
ruby-2.7-builder test: *test_build
ruby-2.7-builder-slim test: *test_build
ruby-2.7 test: *test_build
ruby-2.7-slim test: *test_build
ruby-3.0-builder test: *test_build
ruby-3.0 test: *test_build
ruby-3.1-builder test: *test_build
ruby-3.1 test: *test_build

elixir-1.5: *build_and_deploy
ruby-2.7-builder: *build_and_deploy
ruby-2.7: *build_and_deploy
ruby-2.7-builder-slim: *build_and_deploy
ruby-2.7-slim: *build_and_deploy
ruby-3.0-builder: *build_and_deploy
ruby-3.0: *build_and_deploy
ruby-3.1-builder: *build_and_deploy
ruby-3.1: *build_and_deploy
