# Used for the builder stages of multi-stage docker builds.
# So feel free to add anything that is useful here.
FROM ruby:2.6-alpine

ENV LANG C.UTF-8

RUN apk add --update --no-cache \
    bash \
    build-base \
    git \
    nodejs \
    postgresql-dev \
    tzdata \
    yarn

RUN echo 'gem: --no-document' >> "$HOME/.gemrc" \
 && gem update --system

RUN cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

WORKDIR /app
