FROM ruby:2.3-jessie

ENV LANG C.UTF-8
ENV PHANTOM_VERSION=phantomjs-2.1.1-linux-x86_64

RUN echo 'Europe/Amsterdam' > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

RUN mkdir -p ~/.ssh

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    apt-transport-https \
    wget \
    curl \
    ssh \
    git \
    ca-certificates \
    gnupg2 \
    software-properties-common \
    libmysqlclient-dev \
    libpq-dev \
    libsqlite3-dev \
    pkg-config \
    libssh2-1-dev \
    net-tools

RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add -

RUN apt-key fingerprint 0EBFCD88

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"

RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com E5CEAB0AC5F1CA2A

# Host keys
RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
RUN ssh-keyscan -t rsa gitlab.roqua.nl >> ~/.ssh/known_hosts

RUN echo 'gem: --no-document' >> "$HOME/.gemrc"
RUN gem install bundler --no-document

RUN apt-get update && apt-get install -y \
    dirmngr \
    docker-ce \
    chromedriver \
    chrpath \
    libxft-dev \
    libfreetype6 \
    libfreetype6-dev \
    libfontconfig1 \
    libfontconfig1-dev \
    mysql-client \
    postgresql-client

# Phantom JS
# deprecated, can be removed after all apps moved to selenium driver.
RUN rm -rf /var/lib/apt/lists/* && \
    wget -O - https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xj && \
    mv $PHANTOM_VERSION/bin/phantomjs /usr/local/bin/ && rm -rf $PHANTOM_VERSION/

# Readonly access to our GitLab repositories
COPY read_only_ssh_key /root/.ssh/id_rsa
RUN chown root:root /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN ssh-keygen -y -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pub

WORKDIR /app

# Upgrade packages
RUN apt-get upgrade -y && apt-get autoremove -y && apt-get clean -y

ADD test_load_balancer_status /usr/local/sbin
