# Used for final stages of multi-stage builds.
# Do not add build tools!
FROM ruby:2.6-alpine

ENV LANG C.UTF-8

# Add Alpine packages
# less for pry pager
RUN apk add --update --no-cache \
    bash \
    curl \
    file \
    less \
    postgresql-client \
    tzdata

RUN echo 'gem: --no-document' >> "$HOME/.gemrc" \
 && gem update --system

RUN cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# Add user
RUN addgroup -g 1000 -S app \
 && adduser -u 1000 -S app -G app
USER app

WORKDIR /app

ENV EXECJS_RUNTIME Disabled
