# Used for the builder stages of multi-stage docker builds.
# So feel free to add anything that is useful here.
FROM ruby:2.7-slim

ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    less \
    nodejs \
    libpq-dev \
    tzdata \
    yarn \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'gem: --no-document' >> "$HOME/.gemrc" \
 && gem update --system

RUN cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

WORKDIR /app
