# Used for final stages of multi-stage builds.
# Do not add build tools!

# Issue with sqlite3 on alpine 3.19, fixed to 3.18 for now:
# https://github.com/sparklemotion/sqlite3-ruby/issues/434
FROM ruby:3.2-alpine3.18

ENV LANG C.UTF-8

# Add Alpine packages
# less for pry pager
RUN apk add --update --no-cache \
    bash \
    curl \
    file \
    less \
    postgresql-client \
    tzdata

RUN echo 'gem: --no-document' >> "$HOME/.gemrc" \
 && gem update --system

RUN cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# Add user
RUN addgroup -g 1000 -S app \
 && adduser -u 1000 -S app -G app

WORKDIR /app

RUN chown app:app .

ENV EXECJS_RUNTIME Disabled

USER app
