FROM elixir:1.5

ENV LANG C.UTF-8

RUN cd /tmp && \
    curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    rm nodesource_setup.sh

RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

RUN apt-get update && apt-get install -y nodejs net-tools && apt-get upgrade -y && apt-get autoremove -y && apt-get clean -y

RUN mkdir -p /app
WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force
